### ISSUE TITLE
[ERROR] Swift.DecodingError.typeMismatch 

### ISSUE THREAD

**Issue by alexiscreuzot** [Sherlouk/Odeon#1] opened 2019-01-09 15:00 UTC
iPhone X, iOS 12, Xcode 10.1
I got a `TheMovieDB` API key and put it as environment variable on Odeon scheme.

I get this error on startup: 

```[ERROR] objectMapping(Swift.DecodingError.typeMismatch(Swift.Array<Any>, Swift.DecodingError.Context(codingPath: [CodingKeys<Array<OdeonFilmInCinema>>(stringValue: "data", intValue: nil)], debugDescription: "Expected to decode Array<Any> but found a dictionary instead.", underlyingError: nil)), Status Code: 200, Data Length: 160)```

I tried to fiddle a little with the code but I'm not sure what's going on here.

**Comment by anthonyBertrant** [comment] 2019-01-11 12:13
Same for me and I can't find where the problem is. Maybe API response content are differents that what the program expect to have

**Comment by pixelcodekky** [comment] 2019-01-11 17:04
[ERROR] objectMapping(Swift.DecodingError.typeMismatch(Swift.Array<Any>, Swift.DecodingError.Context(codingPath: [CodingKeys<Array<OdeonFilmInCinema>>(stringValue: "data", intValue: nil)], debugDescription: "Expected to decode Array<Any> but found a dictionary instead.", underlyingError: nil)), Status Code: 200, Data Length: 160)

Debug area show as above issues, how can I solve that thing? or am I need something else?. I used my Moviedb API, it doesn't work.

**Comment by meercha** [comment] 2019-01-15 10:04
Can confirm, having the same problem as above after adding the API key.

**Comment by Sherlouk** [comment] 2019-01-17 17:42
Hi everyone,

First off I just want to apologise for not responding at all since this issue was opened - it appears I'm not watching this repo so I wasn't being notified of any activity and as this project was very much a 'fire and forget' I didn't check up on it. I can only apologise for that and thank the person who tweeted me to take a look here! 👀 

I did a bit of an investigation on this and was able to reproduce it immediately. The request that was failing was 'filmsForCinema' within the `HomeFetcher.swift` which takes the user's chosen cinema ID as a parameter. I defaulted this to `0` (which I actually found within ODEONs own app), what I didn't account for is that ODEON actually has onboarding which makes a user choose a cinema but I unfortunately did not get time to do that.

As a dirty fix I have changed the default cinema to one that actually exists, and you can change it in the settings area (which applies after a hard refresh of the application).

This issue was introduced purely because of an order of operations where I had made the cinema selector (and therefore had stored a cinema in my user defaults) before I made the home screen. As I used the same simulator for the entire project, this issue didn't crop up - but now that I've reset my simulators and started as a fresh user again it was obvious.

So for that I do apologise again, I have just done a quick pass through the app and what was "functional" does seem to still be working 🤞 Thanks for raising the issue!

Fixed by 655f554

**Closed as completed by Sherlouk** 2019-01-17 17:42 UTC
